Updated build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,21 +1,41 @@
 #!/bin/bash
 
-if [[ $# == 0 ]]; then
-	printf "Usage: build <version>\n"
+function error {
+	printf "$1"
+	printf "\n"
 	exit 1
+}
+
+if [[ $# == 0 ]]; then
+	error "Usage: build <version>"
 fi
 
-git checkout --quiet releases || exit 1
-git checkout --quiet BetterUpdating
+# Check branch
+currentBranch=$(git rev-parse --abbrev-ref HEAD)
+if [[ "$currentBranch" == "releases" ]]; then
+ error "You cannot create a release of the $currentBranch branch."
+fi
+
+# Check to see if there are any local changes that will prevent switching branches
+git checkout --quiet releases &> /dev/null || error "Commit any local changes before building."
+git checkout --quiet $currentBranch
+
+exit 1
 
 version=$1
+
+# CHECK FORMAT OF THE TAG
+php -r "if (preg_match('/^\d+\.\d+\.\d+(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?\$/',\$argv[1])) {
+	exit(0);
+} else {
+	exit(1);
+}" $version || error "The version '$version' is an invalid format."
 
 # Check to see if the version is unique
 existingTag=$(git tag -l | grep "^$version$")
 
 if [[ $existingTag != "" ]]; then
-	printf "That version already exists.\n"
-	exit 1
+	error "A release with version $version already exists."
 fi
 
 # Add the tag for the version and build the release
